# Input/output paths
features_root: /home/ubuntu/giodir/digitalPathology/data/features/uni_features_merged_RE_TN
output_dir: /home/ubuntu/giodir/digitalPathology/flare_exp/outputs/binary_diff_first

# Model hyperparameters
model_type: base_mil
attention_dim: 128
hidden_dim: 64
dropout: 0.25
input_dim: 1536
num_classes: 2
output_dim: 1

# Client train hyperparameters
epochs: 2
batch_size: 8
lr: 5e-4
weight_decay: 1e-4
patience: 10
max_bag_size: 0

# Server hyperparameters
client_list:
  - trento_client
  - reggio_client
num_rounds: 2
train_script: flare_exp/client.py
job_name: mil-fedavg
cross_site_eval: false

# Metrics
key_metric: balanced_acc
eval_threshold_metric: balanced_acc
epoch_selection_metric: null


# Runtime/settings
num_workers: 4
seed: 7
